name: lab_b2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Ikoner
  cupertino_icons: ^1.0.8

  # HTTP requests
  http: ^1.1.0

  # Datum och tid formatering
  intl: ^0.18.1

  # Lokalt lagrad data (cache/offline)
  shared_preferences: ^2.1.1

  # Kontrollera internet-anslutning
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
